"""Serve pre-seeded pipeline fixtures so the demo survives a flaky network.

Fixtures are generated by `scripts/seed_demo.py` into `backend/demo_seeds/<slug>/`.
The frontend can load one via `?demo=<slug>` without hitting any live APIs.

Exposed:
- GET /demo                     — list available slugs
- GET /demo/{slug}              — full fixture (transcript + concepts + images + meta)
- GET /demo/{slug}/{filename}   — static file (audio.mp3 or image_NN.jpg)
"""

from __future__ import annotations

import json
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

router = APIRouter()

SEEDS_DIR = Path(__file__).resolve().parent.parent / "demo_seeds"


def _load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


@router.get("/demo")
def list_demos():
    if not SEEDS_DIR.exists():
        return {"demos": []}
    demos = []
    for d in sorted(SEEDS_DIR.iterdir()):
        meta_file = d / "meta.json"
        if not meta_file.exists():
            continue
        demos.append(_load_json(meta_file))
    return {"demos": demos}


@router.get("/demo/{slug}")
def get_demo(slug: str):
    seed_dir = SEEDS_DIR / slug
    if not seed_dir.is_dir():
        raise HTTPException(status_code=404, detail=f"Demo '{slug}' not found")
    try:
        return {
            "meta": _load_json(seed_dir / "meta.json"),
            "transcript": _load_json(seed_dir / "transcript.json"),
            "concepts": _load_json(seed_dir / "concepts.json"),
            "images": _load_json(seed_dir / "images.json"),
            "audio_url": f"/demo/{slug}/audio.mp3",
        }
    except FileNotFoundError as e:
        raise HTTPException(status_code=500, detail=f"Demo '{slug}' is incomplete: {e}")


@router.get("/demo/{slug}/{filename}")
def get_demo_file(slug: str, filename: str):
    # Guard against path traversal: reject anything with separators.
    if "/" in filename or "\\" in filename or ".." in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")
    path = SEEDS_DIR / slug / filename
    if not path.is_file():
        raise HTTPException(status_code=404, detail="File not found")

    media_type = "application/octet-stream"
    if filename.endswith(".mp3"):
        media_type = "audio/mpeg"
    elif filename.endswith((".jpg", ".jpeg")):
        media_type = "image/jpeg"
    elif filename.endswith(".png"):
        media_type = "image/png"
    return FileResponse(path, media_type=media_type)
